export const CDN_URL = "https://cdn.cloudflare.steamstatic.com/apps/dota2/videos/dota_react/heroes/renders";

export const HEROES = [
	"Arc Warden",
	"Batrider",
	"Broodmother",
	"Dazzle",
	"Death Prophet",
	"Dragon Knight",
	"Earth Spirit",
	"Ember Spirit",
	"Huskar",
	"Invoker",
	"Keeper of the Light",
	"Kunkka",
	"Leshrac",
	"Lina",
	"Lone Druid",
	"Meepo",
	"Necrophos",
	"Outworld Destroyer",
	"Pangolier",
	"Primal Beast",
	"Puck",
	"Queen of Pain",
	"Riki",
	"Shadow Fiend",
	"Sniper",
	"Storm Spirit",
	"Templar Assassin",
	"Tinker",
	"Tiny",
	"Viper",
	"Visage",
	"Void Spirit",
	"Windranger",
	"Zeus",
];
